deployment:
  tasks:
    - export DEPLOYPATH=/home/gopius/build.gopius.com/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp -R ./public/assets $DEPLOYPATH
    - /bin/cp ./public/m_server/index.php $DEPLOYPATH
    - /bin/cp ./public/m_server/.htaccess $DEPLOYPATH
    - /bin/ln -s /home/gopius/build.gopius.com/storage/app/public /home/gopius/build.gopius.com/storage