deployment:
  tasks:
    - export DEPLOYPATH=/home/gopius/build.gopius.com/
    - export ASSETDEPLOYPATH=/home/gopius/build.gopius.com/assets
    - export SYMDEPLOYPATH=/home/gopius/build.gopius.com/storage/app/public
    - export SYMTARGETDEPLOYPATH=/home/gopius/build.gopius.com/storage
    - /bin/rm -Rf $ASSETDEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/assets $DEPLOYPATH
    - /bin/cp ./public/m_server/index.php $DEPLOYPATH
    - /bin/cp ./public/m_server/.htaccess $DEPLOYPATH
    - /bin/ln -s $SYMDEPLOYPATH $SYMTARGETDEPLOYPATH